apiVersion: apps/v1
kind: Deployment
metadata: 
  name: wordpress
  namespace: wordpress
spec: 
  replicas: 2
  selector:
    matchLabels: 
      app: wordpress
  strategy: 
    type: Recreate
  template: 
    metadata: 
      labels: 
        app: wordpress
    spec:
      containers: 
      - image: wordpress:latest
        name: wordpress
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env: 
        - name: WORDPRESS_DB_HOST
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: name
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: user
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: wordpress
---
apiVersion: v1
kind: Service
metadata: 
  name: wordpress
  namespace: wordpress
spec: 
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 80
